branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: LandofShadowMap-dev
    group_suffix: null
global:
  application_name: Land of Shadow Map
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
