branch-defaults:
  main:
    environment: Land-of-Shadow-Map-dev
    group_suffix: null
environment-defaults:
  Land-of-Shadow-Map-dev:
    branch: null
    repository: null
global:
  application_name: Land-of-Shadow-Map
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
